version: '3'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bunactyl-docs
    image: bunactyl-docs:local
    x-ports:
      - 80/https
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
